apiVersion: batch/v1
kind: Job
metadata:
  name: dgenclient
  labels:
    app: datagenclient
spec:
  template:
    metadata:
      labels:
        app: datagenclient
    spec:
      containers:
      - name: datagen
        image: qserv/dax_data_generator:tickets-DM-26846
        imagePullPolicy: Always
        command: '/bin/bash -c "/home/qserv/dax_data_generator/scripts/run_datagenclient.sh"'
        args:
        - "--network=host"
        - "--rm"
        - "-u 1000:1000"
      restartPolicy: OnFailure
