apiVersion: batch/v1
kind: Job
metadata:
  name: dgenserver
  labels:
    app: datagenserver
spec:
  template:
    metadata:
      labels:
        app: datagenserver
    spec:
      containers:
      - name: datagen
        image: qserv/dax_data_generator:master
        imagePullPolicy: Always
        command: ["/home/qserv/dax_data_generator/scripts/run_datagenserver.sh"]
        args: ["fakedb", "-glocalhost", "-aCHANGEME", "-k", "-r0:2000"]
        ports:
          - containerPort: 13042
      restartPolicy: Never
