apiVersion: batch/v1
kind: Job
metadata:
  name: dgenclient
  labels:
    app: datagenclient
spec:
  parallelism: 3
  template:
    metadata:
      labels:
        app: datagenclient
    spec:
      hostNetwork: True
      containers:
      - name: datagen
        image: qserv/dax_data_generator:tickets-DM-26846
        imagePullPolicy: Always
        command: ["/home/qserv/dax_data_generator/scripts/run_datagenclient.sh", "-H192.168.1.143", "-r"]
      restartPolicy: Never
