# serverCfg.yml
server:
  port: 13042

fakeDataGenerator:
  arguments: ''
  visits: 30
  objects: 1000
  seed: 1
  transaction_size: 1000
  cfgFileName: fakeGenSpec.py

partitioner:
  cfgDir: partitionerCfgs

ingest:
  host: #INGEST_HOST#
  port: 25080
  authKey: #INGEST_AUTH#
  dbName: kpm50
  cfgDir: ingestCfgs

pregenerated:
  cfgDir: pregenerated


