# serverCfg.yml
server:
  port: 13042

fakeDataGenerator:
# --chunk 3525 --visits 30 --objects 10000 example_spec.py
  arguments: '--visits 30 --objects 1000'
  visits: 30
  objects: 1000
  seed: 1
  baseCfgDir: configs/fakedb
  cfgFileName: fakeGenSpec.py

partitioner:
  cfgDir: partitionerCfgs

ingest:
  host: localhost
  port: 25080
  authKey: ''
  dbName: fakedb
  cfgDir: ingestCfgs


